sudo: required

services:
  - docker

script:
 - docker pull ubuntu:bionic
 - docker --rm -v $(pwd)/:/build/ -w /build/ ubuntu:bionic /bin/bash travis-build.sh

after_success:
  - ls ./
  - echo "######################################"
  - ls ../
  # - wget https://raw.githubusercontent.com/nomad-desktop/nxos-repository-util/master/nxos-repository-util.sh -O nxos-repository-util.sh
  # - chmod +x nxos-repository-util.sh
  # - ./nxos-repository-util.sh upload testing $PWD/AppImageKit/build/libappimage*.deb

after_failure:
  - echo "Failure"

# branches:
  # except:
    # - master

notifications:
  email: false
