sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - realpath

install:
  - docker pull ubuntu:bionic
  - wget https://raw.githubusercontent.com/nomad-desktop/nxos-repository-util/master/nxos-repository-util.sh -O nxos-repository-util.sh
  - chmod +x nxos-repository-util.sh

script:
 - docker run --rm -v $(pwd)/:/build/ -w /build/ ubuntu:bionic /bin/bash travis-build.sh

branches:
  except:
    - master

deploy:
  - provider: script
    script: nxos-repository-util.sh upload testing *.deb
    skip_cleanup: true
    on:
      branch: testing
  - provider: script
    script: nxos-repository-util.sh upload development *.deb
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH != testing

notifications:
  email: false
